package applicant;

import com.learndrools.domain.Applicant;
import com.learndrools.domain.SuggestedRole;
global com.learndrools.constants.RuleEngineConstants ruleEngineConstant;


rule "Suggest Manager Role"
//enabled false
    when
        Applicant(experienceInYears > 10)
        $a: Applicant(currentSalary > 1000000 && currentSalary <= 2500000)
        $s: SuggestedRole()
    then
        //approach 1
        //modify($s){setRole("Manager")};

        //approach 2
        $s.setRole("Manager");
        update($s)
end

rule "Suggest Senior developer Role"
//agenda-group "developer"
enabled (ruleEngineConstant.BOOLEAN_TRUE)
    when
        Applicant(experienceInYears > 5 && experienceInYears <= 10)
        Applicant(currentSalary > 500000 && currentSalary <= 1500000)
        $s: SuggestedRole()
    then
        $s.setRole("Senior Developer");
        update($s)
end

rule "Suggest Developer Role"
//agenda-group "developer"
    when
        Applicant(experienceInYears > 0 && experienceInYears <= 5)
        Applicant(currentSalary > 200000 && currentSalary <= 1000000)
        $s: SuggestedRole()
    then
        $s.setRole("Developer");
        update($s)
end

rule "Perform Manager Action"
//agenda-group "developer"
    when
       $s : (SuggestedRole(role == ruleEngineConstant.MANAGER.toString()) or SuggestedRole(role == ruleEngineConstant.SENIOR_DEVELOPER.toString()))
    then
        System.out.println("Perform " + $s.getRole()  +" Action");
 end